# .github/workflows/R-CMD-check.yaml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: R-CMD-check (ospapputils)

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      # RSPM (RStudio Package Manager) helps with faster and reproducible package installation
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Set up R environment
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # Cache R packages for faster builds
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Path to the ospapputils package DESCRIPTION file
          path: ospapputils/

      # Run R CMD check for the ospapputils package
      - name: Run R CMD check
        run: |
          # Ensure devtools is installed to run check
          install.packages("devtools")
          # Run R CMD check from within the package directory
          devtools::check()
        working-directory: ospapputils/ # Important: run this step from the package directory
